project_id = "qajahmmzqhgboeoorfqj"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.scrape-campaign-tasks]
verify_jwt = false

[functions.refresh-campaign-subscriptions]
verify_jwt = false
