project_id = "qajahmmzqhgboeoorfqj"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.sync-campaign-tasks]
verify_jwt = false

[functions.refresh-active-campaigns]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.public-feed]
verify_jwt = false
