/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ButtonLabRouteImport } from './routes/button-lab'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as JoinreiRouteImport } from './routes/joinrei'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReiRouteImport } from './routes/rei'
import { Route as V1RouteImport } from './routes/v1'
import { Route as AdminMockupsRouteImport } from './routes/admin/mockups'
import { Route as AdminOpsRouteImport } from './routes/admin/ops'
import { Route as CCodeRouteImport } from './routes/c/$code'
import { Route as RCodeRouteImport } from './routes/r/$code'
import { Route as SShareIdRouteImport } from './routes/s/$shareId'
import { Route as UnlimitedPostsIndexRouteImport } from './routes/unlimited-posts/index'
import { Route as UnlimitedPostsReturnRouteImport } from './routes/unlimited-posts/return'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonLabRoute = ButtonLabRouteImport.update({
  id: '/button-lab',
  path: '/button-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinreiRoute = JoinreiRouteImport.update({
  id: '/joinrei',
  path: '/joinrei',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReiRoute = ReiRouteImport.update({
  id: '/rei',
  path: '/rei',
  getParentRoute: () => rootRouteImport,
} as any)
const V1Route = V1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMockupsRoute = AdminMockupsRouteImport.update({
  id: '/admin/mockups',
  path: '/admin/mockups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/admin/ops',
  path: '/admin/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlimitedPostsIndexRoute = UnlimitedPostsIndexRouteImport.update({
  id: '/unlimited-posts/',
  path: '/unlimited-posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlimitedPostsReturnRoute = UnlimitedPostsReturnRouteImport.update({
  id: '/unlimited-posts/return',
  path: '/unlimited-posts/return',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/button-lab': typeof ButtonLabRoute
  '/earn': typeof EarnRoute
  '/joinrei': typeof JoinreiRoute
  '/login': typeof LoginRoute
  '/rei': typeof ReiRoute
  '/v1': typeof V1Route
  '/admin/mockups': typeof AdminMockupsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/c/$code': typeof CCodeRoute
  '/r/$code': typeof RCodeRoute
  '/s/$shareId': typeof SShareIdRoute
  '/unlimited-posts/return': typeof UnlimitedPostsReturnRoute
  '/unlimited-posts/': typeof UnlimitedPostsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/button-lab': typeof ButtonLabRoute
  '/earn': typeof EarnRoute
  '/joinrei': typeof JoinreiRoute
  '/login': typeof LoginRoute
  '/rei': typeof ReiRoute
  '/v1': typeof V1Route
  '/admin/mockups': typeof AdminMockupsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/c/$code': typeof CCodeRoute
  '/r/$code': typeof RCodeRoute
  '/s/$shareId': typeof SShareIdRoute
  '/unlimited-posts/return': typeof UnlimitedPostsReturnRoute
  '/unlimited-posts': typeof UnlimitedPostsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/button-lab': typeof ButtonLabRoute
  '/earn': typeof EarnRoute
  '/joinrei': typeof JoinreiRoute
  '/login': typeof LoginRoute
  '/rei': typeof ReiRoute
  '/v1': typeof V1Route
  '/admin/mockups': typeof AdminMockupsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/c/$code': typeof CCodeRoute
  '/r/$code': typeof RCodeRoute
  '/s/$shareId': typeof SShareIdRoute
  '/unlimited-posts/return': typeof UnlimitedPostsReturnRoute
  '/unlimited-posts/': typeof UnlimitedPostsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/ask'
    | '/button-lab'
    | '/earn'
    | '/joinrei'
    | '/login'
    | '/rei'
    | '/v1'
    | '/admin/mockups'
    | '/admin/ops'
    | '/c/$code'
    | '/r/$code'
    | '/s/$shareId'
    | '/unlimited-posts/return'
    | '/unlimited-posts/'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/ask'
    | '/button-lab'
    | '/earn'
    | '/joinrei'
    | '/login'
    | '/rei'
    | '/v1'
    | '/admin/mockups'
    | '/admin/ops'
    | '/c/$code'
    | '/r/$code'
    | '/s/$shareId'
    | '/unlimited-posts/return'
    | '/unlimited-posts'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/ask'
    | '/button-lab'
    | '/earn'
    | '/joinrei'
    | '/login'
    | '/rei'
    | '/v1'
    | '/admin/mockups'
    | '/admin/ops'
    | '/c/$code'
    | '/r/$code'
    | '/s/$shareId'
    | '/unlimited-posts/return'
    | '/unlimited-posts/'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AskRoute: typeof AskRoute
  ButtonLabRoute: typeof ButtonLabRoute
  EarnRoute: typeof EarnRoute
  JoinreiRoute: typeof JoinreiRoute
  LoginRoute: typeof LoginRoute
  ReiRoute: typeof ReiRoute
  V1Route: typeof V1Route
  AdminMockupsRoute: typeof AdminMockupsRoute
  AdminOpsRoute: typeof AdminOpsRoute
  CCodeRoute: typeof CCodeRoute
  RCodeRoute: typeof RCodeRoute
  SShareIdRoute: typeof SShareIdRoute
  UnlimitedPostsReturnRoute: typeof UnlimitedPostsReturnRoute
  UnlimitedPostsIndexRoute: typeof UnlimitedPostsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-lab': {
      id: '/button-lab'
      path: '/button-lab'
      fullPath: '/button-lab'
      preLoaderRoute: typeof ButtonLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joinrei': {
      id: '/joinrei'
      path: '/joinrei'
      fullPath: '/joinrei'
      preLoaderRoute: typeof JoinreiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rei': {
      id: '/rei'
      path: '/rei'
      fullPath: '/rei'
      preLoaderRoute: typeof ReiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1': {
      id: '/v1'
      path: '/v1'
      fullPath: '/v1'
      preLoaderRoute: typeof V1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mockups': {
      id: '/admin/mockups'
      path: '/admin/mockups'
      fullPath: '/admin/mockups'
      preLoaderRoute: typeof AdminMockupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/admin/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlimited-posts/': {
      id: '/unlimited-posts/'
      path: '/unlimited-posts'
      fullPath: '/unlimited-posts/'
      preLoaderRoute: typeof UnlimitedPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlimited-posts/return': {
      id: '/unlimited-posts/return'
      path: '/unlimited-posts/return'
      fullPath: '/unlimited-posts/return'
      preLoaderRoute: typeof UnlimitedPostsReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AskRoute: AskRoute,
  ButtonLabRoute: ButtonLabRoute,
  EarnRoute: EarnRoute,
  JoinreiRoute: JoinreiRoute,
  LoginRoute: LoginRoute,
  ReiRoute: ReiRoute,
  V1Route: V1Route,
  AdminMockupsRoute: AdminMockupsRoute,
  AdminOpsRoute: AdminOpsRoute,
  CCodeRoute: CCodeRoute,
  RCodeRoute: RCodeRoute,
  SShareIdRoute: SShareIdRoute,
  UnlimitedPostsReturnRoute: UnlimitedPostsReturnRoute,
  UnlimitedPostsIndexRoute: UnlimitedPostsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
